server:
  port: 30752

eureka:
  instance:
    hostname: discovery-service
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 90
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  security:
    enabled: false
spring:
  boot:
    admin:
      context-path: /admin
      
