
server:
  port: 8091

eureka:
  instance:
    hostname: pet-service
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/
      
spring:
  datasource:
    url: jdbc:mysql://mysql-pet:3306/pet?createDatabaseIfNotExist=true&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: c7o2r1e4
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
