server:
  port: 30751

eureka:
  instance:
    hostname: proxy-service
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}   
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-service:30752/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS   
              
zuul:
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
    pet-service:
      path: /pet/**
      serviceId: pet-service
    record-service:
      path: /record/**
      serviceId: record-service
    location-service:
      path: /location/**
      serviceId: location-service
    rule-service:
      path: /rule/**
      serviceId: rule-service
    forum-service:
      path: /forum/**
      serviceId: forum-service
      
hystrix:
  command:
    myusers-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
            
spring:
  data.mongodb:
    uri: mongodb://mongo-auth:27017/auth
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
