
eureka:
  instance:
    hostname: user-service
    instance-id: user-service:${random.uuid}
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}   
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-service:30752/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS   
      
spring:
  data.mongodb:
    uri: mongodb://mongo-cover:27017/cover
  datasource:
    url: jdbc:mysql://mysql-user:3306/user?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: c7o2r1e4
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 0
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
